# https://git.drupalcode.org/project/gitlab_templates/

include:
  # - project: $_GITLAB_TEMPLATES_REPO
    # ref: $_GITLAB_TEMPLATES_REF
    # file:
      # - "/includes/include.drupalci.main.yml"
      # - "/includes/include.drupalci.variables.yml"
      # - "/includes/include.drupalci.workflows.yml"
  - remote: https://git.drupalcode.org/project/gitlab_templates/-/raw/default-ref/includes/include.drupalci.main.yml
  - remote: https://git.drupalcode.org/project/gitlab_templates/-/raw/default-ref/includes/include.drupalci.variables.yml
  - remote: https://git.drupalcode.org/project/gitlab_templates/-/raw/default-ref/includes/include.drupalci.hidden-variables.yml
  - remote: https://git.drupalcode.org/project/gitlab_templates/-/raw/default-ref/includes/include.drupalci.workflows.yml

.skip-phpmd-rule: &skip-phpmd-rule
  if: '$SKIP_PHPMD == "1"'
  when: never

.phpmd-base:
  stage: validate
  rules:
    - !reference [.opt-in-current-rule]
    - *skip-phpmd-rule
    - !reference [.php-files-exist-rule]
  needs:
    - composer
  before_script:
    - curl -fsSL https://phpmd.org/static/latest/phpmd.phar -o vendor/bin/phpmd
    - chmod +x vendor/bin/phpmd
  script:
    - php --version
    - vendor/bin/phpmd --version
    - sed -i "s#/builds/project/display_builder#${CI_PROJECT_DIR}#g" ${_WEB_ROOT}/modules/custom/${CI_PROJECT_NAME}/.phpmd.baseline.xml
    - vendor/bin/phpmd
        $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME
        gitlab
        $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME/.phpmd.xml
        --exclude 'tests/*,**/tests/*'
        --baseline-file $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME/.phpmd.baseline.xml > phpmd-quality-report.json || true
    - vendor/bin/phpmd
        $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME
        text
        $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME/.phpmd.xml
        --exclude 'tests/*,**/tests/*'
        --baseline-file $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME/.phpmd.baseline.xml
  allow_failure: false
  artifacts:
    expose_as: phpmd
    when: always
    expire_in: 6 mos
    reports:
      codequality: phpmd-quality-report.json
    name: artifacts-$CI_PIPELINE_ID-$CI_JOB_NAME_SLUG
    paths:
      - phpmd-quality-report.json

phpmd:
  extends: .phpmd-base
composer-lint:
  allow_failure: false
cspell:
  allow_failure: true
  variables:
    _CSPELL_IGNORE_PATHS: '**/fixtures/*.yml, *.neon, **/*.story.yml, **/build.env, **/*.patch'
eslint:
  allow_failure: false
phpcs:
  allow_failure: false
phpstan:
  allow_failure: true
phpunit:
  allow_failure: false
  variables:
    _PHPUNIT_EXTRA: ''
